import { CarId, SetupValues } from "@/types/setup";
import { getCarById } from "./cars";
import { getTrackById } from "./tracks";

/**
 * Generates a human-readable setup sheet as plain text.
 *
 * Since iRacing .sto files are a proprietary binary format, we can't generate
 * those directly. Instead we produce a clean, printable setup sheet that the
 * user can reference while entering values in the iRacing garage.
 */
export function generateSetupSheet(
  carId: CarId,
  trackId: string,
  values: SetupValues,
  name?: string,
): string {
  const car = getCarById(carId);
  const track = getTrackById(trackId);
  if (!car || !track) throw new Error("Invalid car or track ID");

  const setupName = name ?? `${car.name} — ${track.name}`;
  const lines: string[] = [];

  lines.push("╔══════════════════════════════════════════════════════════════╗");
  lines.push("║            RACEDEX.GG SETUP SHEET                           ║");
  lines.push("╠══════════════════════════════════════════════════════════════╣");
  lines.push(`║  Setup:  ${setupName.padEnd(50)}║`);
  lines.push(`║  Car:    ${car.name.padEnd(50)}║`);
  lines.push(`║  Series: ${car.series.padEnd(50)}║`);
  lines.push(`║  Track:  ${track.name.padEnd(50)}║`);
  lines.push(`║  Type:   ${track.type.padEnd(50)}║`);
  lines.push("╠══════════════════════════════════════════════════════════════╣");

  for (const group of car.parameters) {
    lines.push("║                                                              ║");
    lines.push(`║  ── ${group.group.toUpperCase()} ${"─".repeat(Math.max(0, 53 - group.group.length))}║`);

    for (const param of group.params) {
      const val = values[param.key] ?? param.defaultValue;
      const display = typeof val === "number" ? formatValue(val, param.unit) : String(val);
      const label = param.label.padEnd(35);
      const value = `${display} ${param.unit}`.padEnd(22);
      lines.push(`║  ${label} ${value} ║`);
    }
  }

  lines.push("║                                                              ║");
  lines.push("╠══════════════════════════════════════════════════════════════╣");
  lines.push("║  Generated by RaceDex.gg Setup Builder                      ║");
  lines.push(`║  ${new Date().toLocaleString().padEnd(58)}║`);
  lines.push("╚══════════════════════════════════════════════════════════════╝");

  return lines.join("\n");
}

function formatValue(val: number, unit: string): string {
  if (unit === "clicks" || unit === "%") return val.toFixed(1).replace(/\.0$/, "");
  if (unit === ":1") return val.toFixed(2);
  if (unit === "psi" || unit === "deg" || unit === "in") return val.toFixed(2);
  return val.toFixed(1);
}

/**
 * Generates a JSON export of the setup that can be saved and re-imported.
 */
export function generateSetupJSON(
  carId: CarId,
  trackId: string,
  values: SetupValues,
  name?: string,
): string {
  const car = getCarById(carId);
  const track = getTrackById(trackId);
  if (!car || !track) throw new Error("Invalid car or track ID");

  const exportData = {
    version: "1.0",
    generator: "RaceDex.gg Setup Builder",
    generated: new Date().toISOString(),
    name: name ?? `${car.name} — ${track.name}`,
    car: { id: carId, name: car.name, series: car.series },
    track: { id: trackId, name: track.name, type: track.type },
    parameters: {} as Record<string, { label: string; value: number; unit: string; group: string }>,
  };

  for (const group of car.parameters) {
    for (const param of group.params) {
      exportData.parameters[param.key] = {
        label: param.label,
        value: values[param.key] ?? param.defaultValue,
        unit: param.unit,
        group: group.group,
      };
    }
  }

  return JSON.stringify(exportData, null, 2);
}
